volumes:
  db-data:

services:
  backend:
    build:
      context: .
      dockerfile: docker/local/php/Dockerfile
    container_name: backend
    ports:
      - 8765:8765
    volumes:
      - ./backend:/src
      # https://windows.php.net/download#php-8.4
      - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/local/mssql/Dockerfile
    container_name: db
    user: root
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
    volumes:
      - ./logs/db:/var/opt/mssql/log
      - db-data:/var/opt/mssql
    command: [ "/bin/bash", "-c", "chmod +x /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh" ]
