volumes:
  # db-data: # SQL Server の場合
  db-mysql-data: # MySQL の場合

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/local/node/Dockerfile
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/src
      - ./logs/frontend:/root/.npm/_logs
    stdin_open: true
    tty: true
  backend:
    build:
      context: .
      dockerfile: docker/local/php/Dockerfile
    container_name: backend
    ports:
      - 8765:8765
    volumes:
      - ./backend:/src
      # https://windows.php.net/download#php-8.4
      - ./docker/local/php/php.ini:/etc/php.d/php.ini
    depends_on:
      - db
  # SQL Server の場合
  # db:
  #   build:
  #     context: .
  #     dockerfile: docker/local/mssql/Dockerfile
  #   container_name: db
  #   user: root
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - MSSQL_SA_PASSWORD=Passw0rd
  #   volumes:
  #     - ./logs/db:/var/opt/mssql/log
  #     - db-data:/var/opt/mssql
  #   command:
  #     [
  #       "/bin/bash",
  #       "-c",
  #       "chmod +x /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh",
  #     ]
  # MySQL の場合
  db:
    build:
      context: .
      dockerfile: docker/local/mysql/Dockerfile
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=StudyCakePHP
      - MYSQL_USER=default
      - MYSQL_PASSWORD=Passw0rd
      - MYSQL_ROOT_PASSWORD=Passw0rd
    volumes:
      - ./logs/db:/var/log/mysql
      - db-mysql-data:/var/lib/mysql
