name: FrontendCI

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main", "develop"]
    paths:
      - "frontend/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install
      - name: Format check
        run: npm run format-check
      - name: Lint check
        run: npm run lint
      - name: Type check
        run: npm run type-check
      - name: Build
        run: npm run build-only
